import 'dart:io';

void main() {
  final file = File('/Users/moseonghwan/code/archiverse/lib/pages/professor/home/home_widget.dart');
  final lines = file.readAsLinesSync();

  // Find start: line 1752 (index 1751)
  // Find end: line 4127 (index 4126) - the closing of Column children

  final beforeTable = lines.sublist(0, 1751);
  final afterTable = lines.sublist(4127);

  // New DataTable2 code
  final newTableCode = [
    '                                                                          child:',
    '                                                                              DataTable2(',
    '                                                                            columnSpacing: 12,',
    '                                                                            horizontalMargin: 12,',
    '                                                                            minWidth: 600,',
    '                                                                            headingRowHeight: 56,',
    '                                                                            dataRowHeight: 52,',
    '                                                                            headingRowColor: WidgetStateProperty.all(',
    '                                                                              Color(0xFF284E75),',
    '                                                                            ),',
    '                                                                            columns: [',
    '                                                                              DataColumn2(',
    '                                                                                label: Text(',
    '                                                                                  \'학생\',',
    '                                                                                  style: FlutterFlowTheme.of(context).labelLarge.override(',
    '                                                                                    font: GoogleFonts.openSans(',
    '                                                                                      color: Colors.white,',
    '                                                                                      fontWeight: FontWeight.w600,',
    '                                                                                    ),',
    '                                                                                    fontSize: 14.0,',
    '                                                                                    color: Colors.white,',
    '                                                                                  ),',
    '                                                                                ),',
    '                                                                                size: ColumnSize.L,',
    '                                                                              ),',
    '                                                                              DataColumn2(',
    '                                                                                label: Text(',
    '                                                                                  \'중간 결과물\',',
    '                                                                                  style: FlutterFlowTheme.of(context).labelLarge.override(',
    '                                                                                    font: GoogleFonts.openSans(',
    '                                                                                      color: Colors.white,',
    '                                                                                      fontWeight: FontWeight.w600,',
    '                                                                                    ),',
    '                                                                                    fontSize: 14.0,',
    '                                                                                    color: Colors.white,',
    '                                                                                  ),',
    '                                                                                ),',
    '                                                                                size: ColumnSize.M,',
    '                                                                              ),',
    '                                                                              DataColumn2(',
    '                                                                                label: Text(',
    '                                                                                  \'기말 결과물\',',
    '                                                                                  style: FlutterFlowTheme.of(context).labelLarge.override(',
    '                                                                                    font: GoogleFonts.openSans(',
    '                                                                                      color: Colors.white,',
    '                                                                                      fontWeight: FontWeight.w600,',
    '                                                                                    ),',
    '                                                                                    fontSize: 14.0,',
    '                                                                                    color: Colors.white,',
    '                                                                                  ),',
    '                                                                                ),',
    '                                                                                size: ColumnSize.M,',
    '                                                                              ),',
    '                                                                            ],',
    '                                                                            rows: _getUniqueStudentNames().map((studentName) {',
    '                                                                              final midtermStatus = _getMidtermSubmitStatus(studentName);',
    '                                                                              final finalStatus = _getFinalSubmitStatus(studentName);',
    '                                                                              ',
    '                                                                              return DataRow2(',
    '                                                                                cells: [',
    '                                                                                  DataCell(',
    '                                                                                    Text(',
    '                                                                                      studentName,',
    '                                                                                      style: FlutterFlowTheme.of(context).bodyMedium.override(',
    '                                                                                        font: GoogleFonts.openSans(',
    '                                                                                          fontWeight: FontWeight.w500,',
    '                                                                                        ),',
    '                                                                                        fontSize: 13.0,',
    '                                                                                      ),',
    '                                                                                    ),',
    '                                                                                  ),',
    '                                                                                  DataCell(',
    '                                                                                    Container(',
    '                                                                                      padding: EdgeInsets.symmetric(horizontal: 12, vertical: 6),',
    '                                                                                      decoration: BoxDecoration(',
    '                                                                                        color: midtermStatus == \'제출\'',
    '                                                                                            ? Color(0xFF4CAF50).withOpacity(0.1)',
    '                                                                                            : Colors.transparent,',
    '                                                                                        borderRadius: BorderRadius.circular(6),',
    '                                                                                        border: Border.all(',
    '                                                                                          color: midtermStatus == \'제출\'',
    '                                                                                              ? Color(0xFF4CAF50)',
    '                                                                                              : FlutterFlowTheme.of(context).alternate,',
    '                                                                                          width: 1,',
    '                                                                                        ),',
    '                                                                                      ),',
    '                                                                                      child: Text(',
    '                                                                                        midtermStatus,',
    '                                                                                        style: FlutterFlowTheme.of(context).bodyMedium.override(',
    '                                                                                          font: GoogleFonts.openSans(',
    '                                                                                            color: midtermStatus == \'제출\'',
    '                                                                                                ? Color(0xFF4CAF50)',
    '                                                                                                : FlutterFlowTheme.of(context).secondaryText,',
    '                                                                                            fontWeight: FontWeight.w600,',
    '                                                                                          ),',
    '                                                                                          fontSize: 12.0,',
    '                                                                                        ),',
    '                                                                                      ),',
    '                                                                                    ),',
    '                                                                                  ),',
    '                                                                                  DataCell(',
    '                                                                                    Container(',
    '                                                                                      padding: EdgeInsets.symmetric(horizontal: 12, vertical: 6),',
    '                                                                                      decoration: BoxDecoration(',
    '                                                                                        color: finalStatus == \'제출\'',
    '                                                                                            ? Color(0xFF2196F3).withOpacity(0.1)',
    '                                                                                            : Colors.transparent,',
    '                                                                                        borderRadius: BorderRadius.circular(6),',
    '                                                                                        border: Border.all(',
    '                                                                                          color: finalStatus == \'제출\'',
    '                                                                                              ? Color(0xFF2196F3)',
    '                                                                                              : FlutterFlowTheme.of(context).alternate,',
    '                                                                                          width: 1,',
    '                                                                                        ),',
    '                                                                                      ),',
    '                                                                                      child: Text(',
    '                                                                                        finalStatus,',
    '                                                                                        style: FlutterFlowTheme.of(context).bodyMedium.override(',
    '                                                                                          font: GoogleFonts.openSans(',
    '                                                                                            color: finalStatus == \'제출\'',
    '                                                                                                ? Color(0xFF2196F3)',
    '                                                                                                : FlutterFlowTheme.of(context).secondaryText,',
    '                                                                                            fontWeight: FontWeight.w600,',
    '                                                                                          ),',
    '                                                                                          fontSize: 12.0,',
    '                                                                                        ),',
    '                                                                                      ),',
    '                                                                                    ),',
    '                                                                                  ),',
    '                                                                                ],',
    '                                                                              );',
    '                                                                            }).toList(),',
    '                                                                          ),',
  ];

  final newLines = [...beforeTable, ...newTableCode, ...afterTable];

  file.writeAsStringSync(newLines.join('\n') + '\n');

  print('✅ Replaced ${4127 - 1751} lines with ${newTableCode.length} lines');
  print('   Before: ${lines.length} lines');
  print('   After: ${newLines.length} lines');
  print('   Reduced by: ${lines.length - newLines.length} lines');
}
