import '/core/responsive_wrapper.dart';
        body: ResponsiveWrapper(
          child: SafeArea(
              Container(
                            Flexible(
                                                                          22.0,
                                                                          22.0,
                                                                          22.0,
                                                                          22.0,
                                                                          22.0,
                                                                              fontSize: 22.0,
                                                                                      fontSize: 22.0,
                                                                                            fontSize: 22.0,
                                                                                      fontSize: 22.0,
                                                                                            fontSize: 22.0,
                                                                                      fontSize: 22.0,
                                                                                            fontSize: 22.0,
                                                                                      fontSize: 22.0,
                                                                                                fontSize: 22.0,
                                                                                      fontSize: 22.0,
                                                                                                fontSize: 22.0,
                                                                                      fontSize: 22.0,
                                                                                                fontSize: 22.0,
                                true)
                                true)
                                                  fontSize: 22.0,
                                                                              22.0,
                                                                          22.0,
                                                          Flexible(
                                                                    true,
                                                                              22.0,
                                                                              fontSize: 16.0,
                                                                              fontSize: 16.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 16.0,
                                                                                              fontSize: 16.0,
                                                                              22.0,
                                                                              fontSize: 16.0,
                                                                              fontSize: 16.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 16.0,
                                                                                              fontSize: 16.0,
                                                                              22.0,
                                                                              fontSize: 16.0,
                                                                              fontSize: 16.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 16.0,
                                                                                              fontSize: 16.0,
                                true)
                                                  fontSize: 22.0,
                                                                              22.0,
                                                                          22.0,
                                                                                16.0,
                                                                                fontSize: 16.0,
                                                                            22.0,
                                                                                16.0,
                                                                                16.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 16.0,
                                                                                              fontSize: 16.0,
                                true)
                                                  fontSize: 22.0,
                                                                              22.0,
                                                                          22.0,
                                                                                16.0,
                                                                                fontSize: 16.0,
                                                                            22.0,
                                                                                16.0,
                                                                                16.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 16.0,
                                                                                              fontSize: 16.0,
                                true)
                                                  fontSize: 22.0,
                                                                              22.0,
                                                                          22.0,
                                                                                16.0,
                                                                                fontSize: 16.0,
                                                                            22.0,
                                                                                16.0,
                                                                                16.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 12.0,
                                                                                              fontSize: 16.0,
                                                                                              fontSize: 16.0,
        ),
